- name: 'Create user for Prometheus Node Exporter'
  shell: |
    sudo useradd --no-create-home node_exporter

- name: 'Install Node Exporter Binaries'
  shell: |
    wget https://github.com/prometheus/node_exporter/releases/download/v1.5.0/node_exporter-1.5.0.linux-amd64.tar.gz
    tar xzf node_exporter-1.5.0.linux-amd64.tar.gz
    sudo cp node_exporter-1.5.0.linux-amd64/node_exporter /usr/local/bin/node_exporter
    rm -rf node_exporter-1.5.0.linux-amd64.tar.gz node_exporter-1.5.0.linux-amd64

- name: 'Configure a Service'
  become: true
  copy:
    src: roles/configure-prometheus-node-exporter/files/node_exporter.service
    dest: /etc/systemd/system/node_exporter.service

- name: 'Configure Systemd'
  shell: |
    sudo systemctl daemon-reload
    sudo systemctl enable node_exporter
    sudo systemctl start node_exporter
    sudo systemctl status node_exporter